name: Generate Tags and Deploy to Pages

# Trigger this workflow on every push to the main branch
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the source code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install required Python packages
    - name: Install dependencies
      run: |
        pip install torch torchvision pillow numpy

    # Step 4: Run your tagging script to generate tags.json
    - name: Run tag script
      run: |
        python tag.py

    # Step 5: Deploy the current directory to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./                 # Deploy root folder
        enable_jekyll: false            # Prevent GitHub Pages from ignoring index.html
